# Generated by Django 6.0.5 on 2026-05-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("scope", models.CharField(max_length=20)),
                ("activity_value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("normalized_unit", models.CharField(max_length=50)),
                ("emission_factor", models.FloatField(blank=True, null=True)),
                ("calculated_emission", models.FloatField(blank=True, null=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("locked_for_audit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingestion.datasource",
                    ),
                ),
            ],
        ),
    ]
